version: 1
formatters:
  simple:
    format: "%(message)s"
  normalFormatter:
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "user_id": "%(user_id)s", "message": "%(message)s", "user_message": "%(user_message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
  normalFormatter:
    class: logging.StreamHandler
    formatter: normalFormatter
    level: INFO

loggers:
  __main__:
    level: INFO
    handlers: [console, normalFormatter]
    propagate: no

root:
  level: INFO
  handlers: [console, normalFormatter]
